services:
  haproxy:
    image: haproxy:3.1.5
    labels:
      - "turkis.ignore=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./cert-storage:/usr/local/etc/haproxy/certs:rw
      - ./webroot-storage:/var/www/lego:rw
      - ./haproxy-socket:/var/run/haproxy:rw
    # Add user root to ensure proper socket permissions
    user: root
    networks:
      - turkis-network

  monitor:
    image: ghcr.io/ameistad/turkis-monitor:latest
    labels:
      - "turkis.ignore=true"
    container_name: monitor
    # Add group_add to allow Docker socket access for the golang docker client.
    group_add:
      - "${DOCKER_GID:-999}"  # Default to 999 if not set
    volumes:
      - ./config:/config
      - ./haproxy-socket:/var/run/haproxy:rw
      - ./cert-storage:/usr/local/etc/haproxy/certs:rw
      - ./webroot-storage:/var/www/lego:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - TURKIS_CONFIG_PATH=/config
      # Set to true to use staging server for testing (for Let's Encrypt)
      - LEGO_STAGING=${LEGO_STAGING:-false}
    # Set user to root to ensure proper permissions for certificate directories
    user: root
    networks:
      - turkis-network
    depends_on:
      - haproxy

networks:
  turkis-network:
    name: turkis-public
    external: true
