services:
  haproxy:
    image: haproxy:3.1.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - cert-storage:/usr/local/etc/haproxy/certs:rw
      - webroot-storage:/var/www/lego:rw
      - haproxy-socket:/var/run/haproxy
    networks:
      - turkis-network

  monitor:
    image: ghcr.io/ameistad/turkis-monitor:latest
    container_name: monitor
    volumes:
      - ./config:/config
      - haproxy-socket:/var/run/haproxy
      - cert-storage:/etc/haproxy/certs:rw
      - webroot-storage:/var/www/lego:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - TURKIS_CONFIG_PATH=/config
      # Set to true to use staging server for testing (for Let's Encrypt)
      - LEGO_STAGING=${LEGO_STAGING:-false}
      # TLS is now configured via container labels - see apps.yml
    networks:
      - turkis-network
    depends_on:
      - haproxy

volumes:
  cert-storage:
  haproxy-socket:
  webroot-storage:

networks:
  turkis-network:
    name: turkis-network
    # Use the external option if the network is created separately,
    # otherwise it will be created by this docker-compose file
    # external: true
